// PM Simulator - Auto Version Generator Script
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const versionFilePath = path.join(rootDir, "web", "old", "v1", "src", "version.js");

let commitHash = "dev";
try {
  commitHash = execSync("git rev-parse --short HEAD", { cwd: rootDir, encoding: "utf-8" }).trim();
} catch {
  console.warn("⚠️ Git commit hash could not be retrieved. Using fallback 'dev'.");
}

const fileContent = `// Auto-generated by scripts/update_version.js
export const APP_VERSION = "${commitHash}";
`;

fs.writeFileSync(versionFilePath, fileContent, "utf-8");
console.log(`✅ Updated version.js with commit hash: ${commitHash}`);
